sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=dev

fast_finish: true
include:
  - env: TOXENV=qa
    python: 3.7

allow_failures:
  - env: DJANGO=dev
  - env: DJANGO=1.8

exclude:
  # Python/Django combinations that aren't officially supported
  - { env: DJANGO=1.11, python: 3.7 }
  - { env: DJANGO=2.1, python: 2.7 }
  - { env: DJANGO=2.1, python: 3.4 }
  - { env: DJANGO=2.2, python: 2.7 }
  - { env: DJANGO=2.2, python: 3.4 }
  - { env: DJANGO=3.0, python: 2.7 }
  - { env: DJANGO=3.0, python: 3.4 }
  - { env: DJANGO=3.0, python: 3.5 }



install: pip install tox-travis python-coveralls codecov
before_script:
  - |
    if [[ -z $TOXENV ]]; then
      export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | tr -d '.')-django$(echo $DJANGO|tr -d '.')
    fi
  - echo $TOXENV
script: tox -e $TOXENV --
after_success:
  - coveralls
  - codecov


#deploy:
#  provider: pypi
#  user: Apkawa
#  password:
#    # https://docs.travis-ci.com/user/encryption-keys/
#    secure: ''
#  on:
#    tags: true
#    distributions: sdist bdist_wheel
#    repo: Apkawa/{django-app-template}
#    branch: master
